### ISSUE TITLE
Error: Unknown file type

### ISSUE THREAD

**Issue by Hipapheralkus** [LogicalTrust/BurpExifToolScanner#2]
When burp requests file which doesn't exist (e.g. /file.css) to which "HTTP/1.1 404 Not Found" is returned, an issue raised by Passive Scanner saying: "Error: Unknown file type".

For non-existing files, I think information finding should not be raised.

**Comment by mmmds** [comment]
Not found files and other unable to interpret won't be showed as a scan result.
