### ISSUE TITLE
Disabling blacklist for Response tab?

### ISSUE THREAD

**Issue by Hipapheralkus** [LogicalTrust/BurpExifToolScanner#4]
I think the "Ignore result lines" should only be applied to raising issues; but not to the Metadata (ExifTool) tab in Response. In my opinion, the most common use-case is to find low-handing fruit (e.g. specific version of software used to create file; GPS coordinates, ...) but when such issue is found, having access to all the information about specific files is valuable for more detailed insights. Hence going into the Metadata tab checking everything might be more intended functionality for manual review.

Or it can be a checkbox whether you want to use it or not?:)

**Comment by mmmds** [comment]
My idea was to give the choice to read metadata in issues and the response tab independently. I can see your way of usage and I agree with you. I will work on that.

**Comment by mmmds** [comment]
New version is ready.
